import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source = readFileSync(new URL('../js/cap_seq_to_video.js', import.meta.url), 'utf8');
const listeners = new Map();
const api = {addEventListener:(name, fn)=>listeners.set(name, fn), apiURL:url=>url};
const app = {};
const makeNode = () => ({comfyClass:'CAP_H3VideoGenerator', _stvRoot:{classList:{add(){}}, appendChild(){}},
    _stvProgress:{setStatus(value){this.value=value;}}});
const first = makeNode(), other = makeNode();
const graph = (id,node)=>({id,getNodeById:()=>node});
app.rootGraph = graph('other', other);
const createPreviewPlayer = () => ({root:{style:{},remove(){}},update(data){this.frame=data;},dispose(){}});
const body = source.slice(source.indexOf('const PLAYER_NODES'), source.indexOf('function clampWidth'));
const {restoreGenerator} = new Function('app','api','createPreviewPlayer','t','_loadVideo',
    body+'; return {restoreGenerator};')(app,api,createPreviewPlayer,(key,args)=>args,
    (node,url)=>{node.loaded=url;});
const emit = (name, detail)=>listeners.get(name)({detail});
const base = {workflow_id:'first',node_id:'7',prompt_id:'run1'};
emit('cat_h3_progress',{...base,percent:25,clip_index:1,clip_total:2,phase:'sample'});
emit('cat_h3_preview_started',{...base,preview_id:'7::h3:run1_0'});
emit('kj_preview_override',{node_id:'7::h3:run1_0',image:'frame1',step:2});
assert.equal(other._stvProgress.value, undefined, 'same node ID in another workflow must not receive progress');
assert.equal(other._stvSampling, undefined);
app.rootGraph = graph('first',first);
restoreGenerator(first);
assert.equal(first._stvProgress.value.percent,25);
assert.equal(first._stvSampling.frame.image,'frame1');
app.rootGraph = graph('other',other);
emit('kj_preview_override',{node_id:'7::h3:run1_0',image:'frame2',step:3});
const recreated = makeNode();
app.rootGraph = graph('first',recreated);
restoreGenerator(recreated);
assert.equal(recreated._stvSampling.frame.image,'frame2','latest hidden-tab frame is restored');
app.rootGraph = graph('other',other);
emit('cat_h3_video_ready',{...base,video:{filename:'new.mp4',type:'output'}});
emit('cat_h3_progress',{...base,percent:100,clip_index:2,clip_total:2,phase:'done'});
emit('kj_preview_override',{node_id:'7::h3:run1_0',image:'late',step:4});
const completed = makeNode();
app.rootGraph = graph('first',completed);
restoreGenerator(completed);
assert(completed.loaded.includes('new.mp4'));
assert.equal(completed._stvProgress.value.percent,100);
assert(!completed._stvSampling, 'late preview must not replace completed output');
emit('cat_h3_progress',{...base,prompt_id:'run2',percent:0,phase:'prepare'});
const fresh = makeNode();
app.rootGraph = graph('first',fresh);
restoreGenerator(fresh);
assert.equal(fresh.loaded,undefined,'new execution must not recover previous execution output');
console.log('H3 preview restore: workflow isolation, hidden updates, recreated nodes, completion and late frames passed');
