import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const source = readFileSync(new URL('../js/CapTimelineEditorApp.js', import.meta.url), 'utf8');
const start = source.indexOf('    _dismissContextMenuOutside(');
const end = source.indexOf('\n    }', start) + 6;
const dismiss = new Function(`return ({${source.slice(start, end)}})._dismissContextMenuOutside`)();
const item = {};
let visible = true;
const menu = { contains: target => target === item, remove() { visible = false; } };
const app = { _overlay: { querySelector: () => visible ? menu : null }, _ignoreCtxCloseOnce: true };
dismiss.call(app, { target: item });
assert(visible, 'menu items must still receive their click');
dismiss.call(app, { target: {} });
assert.equal(visible, false, 'first outside pointerdown dismisses even if click bubbling is stopped');
assert.equal(app._ignoreCtxCloseOnce, false);
dismiss.call(app, { target: {} });
assert.match(source, /addEventListener\("pointerdown", this\._onContextPointerDown[^\n]+, true\)/);
assert.match(source, /removeEventListener\("pointerdown", this\._onContextPointerDown, true\)/);
console.log('Context menu: first outside click, inside actions and capture-listener cleanup passed');
