import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source = readFileSync(new URL('../js/editor/KeyframeRun.js', import.meta.url), 'utf8');
const {parseIntervalSelection, keyframeIntervals, addKeyframeVideo, selectedKeyframeRun} = new Function('makeT', source.replace(/^import .*;\r?\n/gm, '').replaceAll('export ', '') + '\nreturn {parseIntervalSelection, keyframeIntervals, addKeyframeVideo, selectedKeyframeRun};')(() => () => '');
const selected = parseIntervalSelection('1,3,5-90', 100);
assert(selected.has(90)); assert(!selected.has(91)); assert(!selected.has(2)); assert.equal(selected.size, 88);
assert.equal(parseIntervalSelection('', 10), null);
assert.deepEqual([...parseIntervalSelection('1，3-5', 10)], [1,3,4,5]);
for (const value of ['0', '5-3', '1,,2', '1.5', 'abc']) assert.throws(() => parseIntervalSelection(value, 100));
assert.equal(parseIntervalSelection('5-9000000000', 90).size, 86);
const intervals = keyframeIntervals(25, 24, [{time: 0, description: 'one'}, {time: 5, description: 'two'}, {time: 25, description: 'end'}]);
assert.deepEqual(intervals.map(row => [row.start_frame, row.end_frame]), [[0,120], [120,600]]);
const segment = {start_frame: 120, end_frame: 360, fps: 24, output_fps: 48, trim_frames: 44, raw_frames: 554};
const video = {keyframe_segment: segment};
let rows = addKeyframeVideo([{file: 'first.mp4', enabled: true, edit_start_sec: 0, trim_out_sec: 5}], video, 'second.mp4', 'id');
assert.equal(rows[0].edit_start_sec, 5); assert.equal(rows[0].trim_out_sec - rows[0].trim_in_sec, 10);
assert.equal(rows[1].enabled, true, 'adjacent segments remain enabled');
assert.equal(addKeyframeVideo(rows, video, 'second.mp4', 'id2'), rows, 'replayed completion does not reset trims');
rows = addKeyframeVideo(rows, video, 'replacement.mp4', 'id3');
assert.equal(rows[1].enabled, false, 'rerunning an interval disables the overlapping previous take');
assert.equal(rows[2].enabled, true);
console.log('Keyframe ranges include both endpoints; intervals, alignment, trims and replay passed.');

const clip={id:'selected-clip',startTime:20,duration:12,track:{locked:false}};
const points=[{time:0,description:'first'},{time:4,description:'middle'},{time:9,description:'last'}];
let target={clip,local:true,start:0,rate:1};
const meta={agent:'MiniMaxH3'};
const editor={getFps:()=>24,_ensureClipMeta:()=>meta,_directorKeyframes:{
    selectedTarget:()=>target,target:()=>target,points:()=>points,selection:{point:points[1]}}};
let request=selectedKeyframeRun(editor);
assert.equal(request.action,'normal');
assert.equal(request.keyframe_runs.length,1);
assert.equal(request.keyframe_runs[0].clip_start_ms,20000);
assert.deepEqual(request.keyframe_runs[0].intervals,[{start_frame:96,end_frame:216,prompt:'middle'}]);
editor._directorKeyframes.selection.point=points[2];
assert.equal(selectedKeyframeRun(editor).keyframe_runs[0].intervals[0].end_frame,288);
clip.track.locked=true; assert.equal(selectedKeyframeRun(editor),null); clip.track.locked=false;
meta.agent='other'; assert.equal(selectedKeyframeRun(editor),null); meta.agent='MiniMaxH3';
target=null; assert.equal(selectedKeyframeRun(editor),null);
target={clip,local:false,start:10,rate:2,media:{id:'source'}};
points.splice(0,points.length,{time:10,description:'first'},{time:18,description:'middle'},{time:28,description:'last'});
editor._directorKeyframes.selection.point=points[1];
request=selectedKeyframeRun(editor);
assert.deepEqual(request.keyframe_runs[0].intervals,[{start_frame:96,end_frame:216,prompt:'middle'}]);
assert.deepEqual(request.keyframe_runs[0].reference,{id:'source',start:10,rate:2});
const appSource=readFileSync(new URL('../js/CapTimelineEditorApp.js',import.meta.url),'utf8');
const start=appSource.indexOf('    async _runSelectedKeyframeDownstream() {');
const runSelected=new Function('selectedKeyframeRun','return ({'+appSource.slice(start,appSource.indexOf('\n    }',start)+6)+'})._runSelectedKeyframeDownstream;')(selectedKeyframeRun);
let queued;
editor._hasH3VideoGeneratorDownstream=()=>true;
editor._runAllActiveClipsDownstream=options=>{queued=options;return true;};
assert.equal(await runSelected.call(editor),true);
assert.deepEqual(queued.clips,[clip]);
assert.deepEqual(queued.h3Generation,request);
console.log('Selected keyframe runs only its interval, maps source rate, closes at Clip end and respects selection/lock/model guards');

const captured = {target, point:points[1]};
editor._directorKeyframes.selection = null;
assert.deepEqual(selectedKeyframeRun(editor,captured), request, 'dialog keeps its own keyframe after selection clears');
editor.node = {};
editor._aiOptimizeKeyframe = captured;
editor._queueClipsDownstream = (clips, preview, generation) => ({clips,preview,generation});
const method = name => {
    const start = appSource.indexOf(`    async ${name}(`);
    return new Function('selectedKeyframeRun','isDirectorTrackType','showCapAlert','draftT',
        `return ({${appSource.slice(start,appSource.indexOf('\n    }',start)+6)}}).${name}`)(
        selectedKeyframeRun,()=>true,()=>{},()=> '');
};
const preview = {};
const normal = await method('_runClipDownstream').call(editor,clip,preview);
assert.deepEqual(normal.clips,[clip]);
assert.deepEqual(normal.generation,request);
assert.deepEqual(preview.clipIds,[String(clip.id)]);
const draft = await method('_runH3Stage').call(editor,clip,'draft',captured);
assert.deepEqual(draft.generation,{...request,action:'draft'});
clip.track.locked = true;
assert.equal(await method('_runClipDownstream').call(editor,clip,preview),undefined);
console.log('Keyframe prompt dialog: captured interval used for normal/draft runs, preview association and lock guard passed');
