import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const source = readFileSync(new URL('../js/CapTimelineEditorApp.js', import.meta.url), 'utf8');
const start = source.indexOf('    _toggleClipLastFrame(');
const toggle = new Function(`return ({${source.slice(start, source.indexOf('\n    }', start) + 6)}})._toggleClipLastFrame`)();
const meta = {clipRole: 'first_last', items: [{id:'a',kind:'image'}, {id:'b',kind:'image'}, {id:'c',kind:'video'}, {id:'d',kind:'image',enabled:false}]};
const clip = {id:'clip', track:{locked:false}};
const snapshots = []; let saves = 0, refreshes = 0;
const app = {_ensureClipMeta:()=>meta, _clipItems:m=>m.items, _recordUndo:()=>snapshots.push(structuredClone(meta)), _saveToWidgets:()=>saves++, _refreshClipResourceViews:()=>refreshes++};
app._setClipPreviewItemIndex = (_,index) => { app.selected=index; };
app._syncClipPrimaryAppearance = () => {};
app._scheduleProgramPreview = () => {};
toggle.call(app, clip, 0); assert.equal(meta.lastFrameMediaId, 'a');
assert.deepEqual(meta.items.map(x=>x.id), ['b','c','d','a']);
assert.equal(app.selected, 3);
assert.deepEqual(snapshots[0].items.map(x=>x.id), ['a','b','c','d']);
toggle.call(app, clip, 0); assert.equal(meta.lastFrameMediaId, 'b');
assert.deepEqual(meta.items.map(x=>x.id), ['c','d','a','b']);
assert.equal(snapshots[1].lastFrameMediaId, 'a');
toggle.call(app, clip, 3); assert.equal(meta.lastFrameMediaId, '');
for (const index of [0,1,9]) toggle.call(app,clip,index);
clip.track.locked=true; toggle.call(app,clip,2); clip.track.locked=false;
meta.clipRole='multi_ref'; toggle.call(app,clip,2);
assert.equal(saves,3); assert.equal(refreshes,3);
meta.clipRole='first_last'; meta.items=[{id:'only',kind:'image'},{id:'disabled',kind:'image',enabled:false}];
toggle.call(app,clip,0);
assert.equal(meta.lastFrameMediaId,'only');
assert.deepEqual(meta.items.map(x=>x.id),['only','disabled'],'tail-only does not reorder');
assert.match(source, /lastFrameMediaId: c\.last_frame_media_id/);
assert.match(source, /last_frame_media_id: m\.lastFrameMediaId/);
console.log('PASS: last-frame assignment, automatic ordering, tail-only, cancellation, undo and edit guards');
