import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {defaultPromptTemplates, sortPromptTemplates, validatePromptTemplates, readPromptTemplates, writePromptTemplates, mergePromptTemplates} from '../js/editor/PromptTemplates.js';

const defaults = defaultPromptTemplates();
assert.equal(defaults.items.length, 8);
assert.equal(new Set(defaults.items.map(row => row.id)).size, 8);
assert(defaults.items.every(row => row.text.length > 50));
const data = {schema_version: 1, items: [{id:'a', name:'A', text:'first', stars:1}, {id:'b', name:'B', text:'second', stars:5}, {id:'c', name:'C', text:'third', stars:5}]};
assert.deepEqual(sortPromptTemplates(data.items).map(row => row.id), ['b','c','a']);
assert.deepEqual(data.items.map(row => row.id), ['a','b','c'], 'Sorting preserves stored tie order');
const saved = new Map();
const storage = {getItem:key => saved.get(key) ?? null, setItem:(key,value) => saved.set(key,value)};
assert.equal(readPromptTemplates(storage).items.length, 8);
writePromptTemplates(data, storage);
assert.deepEqual(readPromptTemplates(storage), data);
const imported = JSON.parse(JSON.stringify(data)); imported.items[0].text = 'updated'; imported.items.push({id:'d',name:'D',text:'new',stars:4});
const merged = mergePromptTemplates(data, imported);
assert.equal(merged.items.length, 4); assert.equal(merged.items[0].text, 'updated');
assert.equal(data.items[0].text, 'first', 'Import does not modify the current document before save');
assert.throws(() => validatePromptTemplates({schema_version:1, items:[{name:'bad',text:12}]}));
assert.throws(() => validatePromptTemplates({schema_version:2, items:[]}));
const inline = readFileSync(new URL('../js/components/InlinePromptEditor.js', import.meta.url), 'utf8');
const rangeStart = inline.indexOf('export function assetMentionRanges');
const ranges = new Function(inline.slice(rangeStart, inline.indexOf('\nexport class', rangeStart)).replace('export ', '') + ';return assetMentionRanges;')();
const source = readFileSync(new URL('../js/components/PromptTemplateActions.js', import.meta.url), 'utf8');
const mentionStart = source.indexOf('export function mentionedPromptAssets');
const mentioned = new Function('assetMentionRanges', 'stripPromptComments', source.slice(mentionStart, source.indexOf('\nexport class', mentionStart)).replace('export ', '') + ';return mentionedPromptAssets;')(ranges, text => text.split('\n').filter(line => !line.trimStart().startsWith('//')).join('\n'));
const assets = [{id:'1',name:'角色',description:'short'}, {id:'2',name:'角色长发',description:'long'}, {id:'3',name:'场景',description:'court'}];
assert.deepEqual(mentioned('@角色长发 @角色长发\n//@场景\n@角色',assets).map(asset => asset.id), ['2','1']);
console.log('Prompt templates: eight defaults, stable five-star sorting, persistence, validated import/export and exact uncommented references passed');
