import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source = readFileSync(new URL('../js/editor/KeyframeRun.js', import.meta.url), 'utf8');
const {parseIntervalSelection, keyframeIntervals, addKeyframeVideo} = new Function('makeT', source.replace(/^import .*;\r?\n/gm, '').replaceAll('export ', '') + '\nreturn {parseIntervalSelection, keyframeIntervals, addKeyframeVideo};')(() => () => '');
const selected = parseIntervalSelection('1,3,5-90', 100);
assert(selected.has(90)); assert(!selected.has(91)); assert(!selected.has(2)); assert.equal(selected.size, 88);
assert.equal(parseIntervalSelection('', 10), null);
assert.deepEqual([...parseIntervalSelection('1，3-5', 10)], [1,3,4,5]);
for (const value of ['0', '5-3', '1,,2', '1.5', 'abc']) assert.throws(() => parseIntervalSelection(value, 100));
assert.equal(parseIntervalSelection('5-9000000000', 90).size, 86);
const intervals = keyframeIntervals(25, 24, [{time: 0, description: 'one'}, {time: 5, description: 'two'}, {time: 25, description: 'end'}]);
assert.deepEqual(intervals.map(row => [row.start_frame, row.end_frame]), [[0,120], [120,600]]);
const segment = {start_frame: 120, end_frame: 360, fps: 24, output_fps: 48, trim_frames: 44, raw_frames: 554};
const video = {keyframe_segment: segment};
let rows = addKeyframeVideo([{file: 'first.mp4', enabled: true, edit_start_sec: 0, trim_out_sec: 5}], video, 'second.mp4', 'id');
assert.equal(rows[0].edit_start_sec, 5); assert.equal(rows[0].trim_out_sec - rows[0].trim_in_sec, 10);
assert.equal(rows[1].enabled, true, 'adjacent segments remain enabled');
assert.equal(addKeyframeVideo(rows, video, 'second.mp4', 'id2'), rows, 'replayed completion does not reset trims');
rows = addKeyframeVideo(rows, video, 'replacement.mp4', 'id3');
assert.equal(rows[1].enabled, false, 'rerunning an interval disables the overlapping previous take');
assert.equal(rows[2].enabled, true);
console.log('Keyframe ranges include both endpoints; intervals, alignment, trims and replay passed.');
