import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { applyContinuationSettings, migrateContinuationSettings } from '../js/editor/ClipContinuation.js';
const rows = () => [0,1,2].map(i => ({id: String(i), start_ms: i*5000, duration_ms:5000, reference_previous:i===1, save_latent:false}));
let clips=rows(); applyContinuationSettings([{type:'director',clips}]);
assert.deepEqual(clips.map(c=>c.save_latent),[true,false,false]);
clips=rows(); clips[1].start_ms+=10; applyContinuationSettings([{type:'director',clips}]); assert.equal(clips[0].save_latent,false);
clips=rows(); clips[1].enabled=false; applyContinuationSettings([{type:'director',clips}]); assert.equal(clips[0].save_latent,false);
clips=rows(); clips[0].agent='other'; applyContinuationSettings([{type:'director',clips}]); assert.equal(clips[0].save_latent,false);
clips=rows(); applyContinuationSettings([{type:'director',enabled:false,clips}]); assert.equal(clips[0].save_latent,false);
const old=[{type:'director',clips:[{id:'a',start_ms:0,duration_ms:5000,save_latent:true},{id:'b',start_ms:5000,duration_ms:5000,h3_motion_context_length:0}]}];
const migrated=migrateContinuationSettings(old); assert.equal(migrated[0].clips[1].reference_previous,true); assert.equal(old[0].clips[1].reference_previous,undefined);
old[0].clips[1].reference_previous=false; assert.equal(migrateContinuationSettings(old)[0].clips[1].reference_previous,false);
const source=readFileSync(new URL('../js/CapTimelineEditorApp.js',import.meta.url),'utf8');
const start=source.indexOf('    _onReferencePreviousChange() {');
const change=new Function(`return ({${source.slice(start,source.indexOf('\n    }',start)+6)}})._onReferencePreviousChange`)();
const meta={}; let saves=0,undo=0;
const app={_selClip:{id:'x'},referencePreviousCb:{checked:true,disabled:false},_recordUndo(){undo++},_ensureClipMeta:()=>meta,_saveToWidgets(){saves++}};
change.call(app); assert.equal(meta.h3MotionContextLength,22); assert.equal(meta.referencePrevious,true);
app.referencePreviousCb.checked=false; change.call(app); assert.equal(meta.h3MotionContextLength,0); assert.equal(meta.referencePrevious,false);
app.referencePreviousCb.disabled=true; change.call(app); assert.equal(saves,2); assert.equal(undo,2);
console.log('PASS: continuation dependencies, migration, toggle, undo/save and disabled controls');
