import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source = readFileSync(new URL('../js/editor/H3DraftVersions.js', import.meta.url), 'utf8');
const Manager = new Function(source.slice(source.indexOf('export class ')).replace('export class ', 'return class '))();
const a = {id:'a',track:{type:'image'}}, b = {id:'b',track:{type:'image',locked:true}}, c = {id:'c',track:{type:'image'}};
const version = (id, start = 0) => ({id,file:id+'.mp4',keyframe_segment:{fps:24,start_frame:start,end_frame:start+24}});
const metas = new Map([[a,{h3Drafts:[version('a'),version('a2',24)]}],[b,{h3Drafts:[version('b')]}],[c,{h3Drafts:[{...version('c'),enabled:false}]}]]);
let undo=0,save=0,refresh=0,render=0;
const manager = Object.create(Manager.prototype);
manager.dialog={open:true}; manager.render=()=>render++;
manager.editor={_timeline:{tracks:[{type:'image',clips:[a,b,c]}]},_ensureClipMeta:clip=>metas.get(clip),_recordUndo:()=>undo++, _saveToWidgets:()=>save++,_scheduleProgramPreview:()=>refresh++};
manager.disableAll([a],{fps:24,start_frame:24,end_frame:48});
assert.equal(metas.get(a).h3Drafts[0].enabled,undefined);
assert.equal(metas.get(a).h3Drafts[1].enabled,false);
manager.disableAll();
assert(metas.get(a).h3Drafts.every(row=>row.enabled===false));
assert.equal(metas.get(b).h3Drafts[0].enabled,undefined,'locked track untouched');
assert.equal(metas.get(a).h3Drafts[0].file,'a.mp4','preview files retained');
assert.deepEqual([undo,save,refresh,render],[2,2,2,2]);
manager.disableAll();
assert.equal(undo,2,'already disabled is a no-op');
console.log('PASS: scoped/global disable, locked tracks, single undo/save, retained files and no-op');
